Fix Dockerfile lint issues Add travis checks

diff --git a/kitchen-ansible-x86_64/Dockerfile-gentoo-openrc b/kitchen-ansible-x86_64/Dockerfile-gentoo-openrc
--- a/kitchen-ansible-x86_64/Dockerfile-gentoo-openrc
+++ b/kitchen-ansible-x86_64/Dockerfile-gentoo-openrc
@@ -1,17 +1,37 @@
-FROM mesaguy/gentoo-openrc-kitchen-base-x86_64:latest
+FROM mesaguy/gentoo-openrc-boot-x86_64:latest
 
-# Add your specific Ansible SSH public key. This only works when run via
-# kitchen, when run with the following options in your .kitchen.yml file:
-#
-#    driver_config:
-#      build_options:
-#        build-arg: SSH_KEY=<%= File.read('.kitchen/docker_id_rsa.pub') %>
-#
-ARG SSH_KEY
-RUN echo "$SSH_KEY" >> /home/kitchen/.ssh/authorized_keys
+# Sync portage
+RUN mkdir -p /usr/portage/distfiles /usr/portage/metadata /usr/portage/packages && \
+chown -R portage:portage /usr/portage && \
+emerge-webrsync && \
+# Install sudo and openssh for kitchen
+emerge app-admin/sudo net-misc/openssh && \
+# Cleanup portage, downloaded source files and compile directories
+rm -rf /usr/portage /var/tmp/* && \
+# Purge logs
+rm -rf /var/log/*
+
+# Adjust sshd defaults per kitchen's needs
+RUN test -f /usr/lib64/misc/sftp-server && \
+printf "Subsystem sftp /usr/lib64/misc/sftp-server\\nUseDNS no\\nUsePAM no\\nPasswordAuthentication yes\\nUsePrivilegeSeparation no\\n" > /etc/ssh/sshd_config && \
+# Start SSH on boot
+rc-update add sshd && \
+# Add 'kitchen' user
+if ! getent passwd kitchen; then useradd -d /home/kitchen -m -s /bin/bash -p '*' kitchen; fi && \
+# Allow unlimited sudo privileges to 'kitchen' user
+echo "kitchen ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && echo "Defaults !requiretty" >> /etc/sudoers && \
+# Make 'kitchen' user's authorized_keys file (empty)
+touch /home/kitchen/.ssh/authorized_keys && \
+# Secure 'kitchen' user's authorized_keys file
+chmod 0600 /home/kitchen/.ssh/authorized_keys && \
+# Fix 'kitchen' user's SSH directory permissions
+chown -R kitchen:kitchen /home/kitchen/.ssh
+
+# Expose SSH
+EXPOSE 22
 
 # Image metadata
-LABEL org.label-schema.vendor="MesaGuy" \
+LABEL org.label-schema.vendor="Mesaguy" \
       org.label-schema.name="Gentoo Linux systemd latest rolling-release kitchen-ansible" \
       org.label-schema.description="Image boots Gentoo Linux's latest rolling-release via systemd configured for kitchen ansible testing" \
       com.mesaguy.operatingsystem.eol="false"
